title: Frank Neugebauer's Portfolio
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist / Programmer - started programming in 1983
  <br><br>
  Insurance - started in the industry in 1998
  <br><br>
  <a href="https://www.linkedin.com/in/neuggs/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
